name: grocy docker container

on:
  release:
    types: [published]

jobs:
  build_and_push_latest:
    runs-on: ubuntu-latest
    env:
      GROCY_IMAGE_TAG: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker-compose build
    - run: docker-compose push
